bind:
  host: 0.0.0.0
  port: 8080
logging:
  level: info
db:
  host: mysql
  port: 3306
  user: root
  name: ko
jwt:
  secret: iXDgDaEYBzIzustW
  exp: 480
job:
  timeout: 60
kobe:
  host: kobe
  port: 8080
kotf:
  host: kotf
  port: 8080
grafana:
  host: grafana
  port: 3000
  username: admin
  password: admin
webkubectl:
  host: webkubectl
  port: 8080
cron:
  enable: true
encrypt:
  key: KubeOperator@202
