bind:
  host: 0.0.0.0
  port: 8080
logging:
  level: info
  out_put: fileAndStd
  max_age: 2592000
  rotation: 86400
db:
  host: mysql
  port: 3306
  user: root
  password: U08BAQEBAQHNm6g24wOpMgv34sNpwR5aBVdvFeSE9+6bydHO/WZLvZXlX9rxiY4V
  name: ko
  max_open_conns: 200
  max_idle_conns: 10
jwt:
  secret: iXDgDaEYBzIzustW
  exp: 480
job:
  timeout: 60
kobe:
  host: kobe
  port: 8080
kotf:
  host: kotf
  port: 8080
webkubectl:
  host: webkubectl
  port: 8080
kubepi:
  host: kubepi
  port: 80
  username: admin
  password: kubepi
cron:
  enable: true
encrypt:
  multilevel:
    enable: true
    secret: WjgBAQEBAQG1bkw4r7ZuaKD1klBxrT+zrRk8KWl+7LE0dli3h+a8gl6er0u8Ks1w
    parts:
      - dP3hT7dBQhygBCYW
      - YIi2czL9wv4tQEZD
