version: "2.2"
services:

  ui:
    image: registry.cn-qingdao.aliyuncs.com/kubeoperator/neeko:${KO_TAG}-${OS_ARCH}
    container_name: kubeoperator_ui
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
    healthcheck:
      test: ["CMD", "test", "-f", "/var/run/nginx.pid"]
      interval: 10s
      timeout: 10s
      retries: 20

  server:
    image: registry.cn-qingdao.aliyuncs.com/kubeoperator/server:${KO_TAG}-${OS_ARCH}
    container_name: kubeoperator_server
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
      - ./conf/app.yaml:/etc/ko/app.yaml
      - ./data/backup:/var/ko/data/backup
      - ./data/ko:/var/ko/data
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:8080/api/v1/health"]
      interval: 10s
      timeout: 10s
      retries: 30
    depends_on:
      mysql:
        condition: service_healthy

  kobe:
    image: registry.cn-qingdao.aliyuncs.com/kubeoperator/kobe:${KO_TAG}-${OS_ARCH}
    container_name: kubeoperator_kobe
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
      - ./conf/kobe.yml:/etc/kobe/app.yml
      - ./data/kobe:/var/kobe/data
      - ./data/backup:/var/ko/data/backup
    healthcheck:
      test: ["CMD","kobe-inventory"]
      interval: 10s
      timeout: 10s
      retries: 20

  kotf:
    image: registry.cn-qingdao.aliyuncs.com/kubeoperator/kotf:${KO_TAG}-${OS_ARCH}
    container_name: kubeoperator_kotf
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data/kotf:/var/kotf/data
    healthcheck:
      test: ["CMD","ps", "-ef", "|", "grep","kotf-server"]
      interval: 10s
      timeout: 10s
      retries: 20

  nginx:
    image: registry.cn-qingdao.aliyuncs.com/kubeoperator/nginx:1.23.1-${OS_ARCH}
    container_name: kubeoperator_nginx
    restart: always
    ports:
      - ${KO_PORT}:80
    volumes:
      - /etc/localtime:/etc/localtime
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./conf/wait.sh:/etc/nginx/conf.d/wait.sh
    command: ["/bin/bash","/etc/nginx/conf.d/wait.sh","-t","10","server:8080","--","nginx","-g","daemon off;"]
    healthcheck:
      test: ["CMD", "test", "-f", "/var/run/nginx.pid"]
      interval: 10s
      timeout: 10s
      retries: 30
    depends_on:
      - server

  mysql:
    image: registry.cn-qingdao.aliyuncs.com/kubeoperator/mysql-server:8.0.29-${OS_ARCH}
    container_name: kubeoperator_mysql
    env_file:
      - ./conf/mysql.env
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
      - ./conf/my.cnf:/etc/my.cnf
      - ./conf/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 20

  webkubectl:
    image: registry.cn-qingdao.aliyuncs.com/kubeoperator/webkubectl:v2.10.6-${OS_ARCH}
    container_name: kubeoperator_webkubectl
    restart: always
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime
    healthcheck:
      test: ["CMD","curl","localhost:8080"]
      interval: 10s
      timeout: 10s
      retries: 20

  nexus:
    image: registry.cn-qingdao.aliyuncs.com/kubeoperator/nexus3:3.38.1-02-${OS_ARCH}
    container_name: kubeoperator_nexus
    restart: always
    ports:
      - ${KO_REPO_PORT}:8081
      - ${KO_REGISTRY_PORT}:8082
      - ${KO_REGISTRY_HOSTED_PORT}:8083
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data/nexus-data/:/nexus-data
    healthcheck:
      test: ["CMD","curl","localhost:8081"]
      interval: 10s
      timeout: 10s
      retries: 20

  kubepi:
    image: registry.cn-qingdao.aliyuncs.com/kubeoperator/kubepi-server:${KP_TAG}-${OS_ARCH}
    container_name: kubeoperator_kubepi
    restart: always
    privileged: true
    volumes:
      - ./data/kubepi:/var/lib/kubepi
    healthcheck:
      test: ["CMD","curl","localhost"]
      interval: 10s
      timeout: 10s
      retries: 20