version: "2.2"
services:

  ui:
    image: registry.cn-qingdao.aliyuncs.com/kubeoperator/ui:${KO_TAG}-${OS_ARCH}
    container_name: kubeoperator_ui
    restart: always

  server:
    image: registry.cn-qingdao.aliyuncs.com/kubeoperator/server:${KO_TAG}-${OS_ARCH}
    container_name: kubeoperator_server
    volumes:
      - ./conf/app.yaml:/etc/ko/app.yaml
      - ./data/backup:/var/ko/data/backup
      - ./data/ko:/var/ko/data
    restart: always
    depends_on:
      - mysql

  kobe:
    image: registry.cn-qingdao.aliyuncs.com/kubeoperator/kobe:${KO_TAG}-${OS_ARCH}
    volumes:
      - ./conf/kobe.yml:/etc/kobe/app.yml
      - ./data/kobe:/var/kobe/data
      - ./data/backup:/var/ko/data/backup
    restart: always
    container_name: kubeoperator_kobe

  nginx:
    image: registry.cn-qingdao.aliyuncs.com/kubeoperator/nginx:1.19.9-alpine-${OS_ARCH}
    container_name: kubeoperator_nginx
    restart: always
    ports:
      - ${KO_SERVER_IP}:${KO_PORT}:443
      - ${KO_SERVER_IP}:8081:8081
      - ${KO_SERVER_IP}:8082:8082
      - ${KO_SERVER_IP}:8083:8083
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./cert:/etc/nginx/cert
    command: /bin/sh -c "nginx -g 'daemon off;'"
    depends_on:
      - server

  mysql:
    image: registry.cn-qingdao.aliyuncs.com/kubeoperator/mariadb:10.5.8-alpine-${OS_ARCH}
    container_name: kubeoperator_mysql
    restart: always
    volumes:
      - ./conf/my.cnf:/etc/my.cnf
      - ./data/mysql:/var/lib/mysql

  nexus:
    restart: always
    image: registry.cn-qingdao.aliyuncs.com/kubeoperator/nexus3:3.30.1-${OS_ARCH}
    container_name: kubeoperator_nexus
    volumes:
      - ./data/nexus-data/:/nexus-data
