version: "2.2"
services:

  ui:
    image: registry.cn-qingdao.aliyuncs.com/kubeoperator/ui:${KO_TAG}-${OS_ARCH}
    container_name: kubeoperator_ui
    restart: always
    healthcheck:
      test: ["CMD", "test", "-f", "/var/run/nginx.pid"]
      interval: 10s
      timeout: 10s
      retries: 20

  server:
    image: registry.cn-qingdao.aliyuncs.com/kubeoperator/server:${KO_TAG}-${OS_ARCH}
    container_name: kubeoperator_server
    volumes:
      - ./conf/app.yaml:/etc/ko/app.yaml
      - ./data/backup:/var/ko/data/backup
    restart: always
    healthcheck:
      test: ["CMD-SHELL","ps", "-ef", "|", "grep","ko-server"]
      interval: 10s
      timeout: 10s
      retries: 20
    depends_on:
      mysql:
        condition: service_healthy

  kobe:
    image: registry.cn-qingdao.aliyuncs.com/kubeoperator/kobe:${KO_TAG}-${OS_ARCH}
    volumes:
      - ./data/kobe:/var/kobe/data
      - ./data/backup:/var/ko/data/backup
    restart: always
    container_name: kubeoperator_kobe
    healthcheck:
      test: ["CMD","kobe-inventory"]
      interval: 10s
      timeout: 10s
      retries: 20

  kotf:
    image: registry.cn-qingdao.aliyuncs.com/kubeoperator/kotf:${KO_TAG}-${OS_ARCH}
    container_name: kubeoperator_kotf
    restart: always
    volumes:
      - ./data/kotf:/var/kotf/data
    healthcheck:
      test: ["CMD","ps", "-ef", "|", "grep","kotf-server"]
      interval: 10s
      timeout: 10s
      retries: 20

  nginx:
    image: registry.cn-qingdao.aliyuncs.com/kubeoperator/nginx:1.19.2-${OS_ARCH}
    container_name: kubeoperator_nginx
    restart: always
    ports:
      - ${KO_PORT}:80
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    healthcheck:
      test: ["CMD","curl","-LX","POST","http://server:8080/api/v1/auth/login/","|","grep","data"]
      interval: 10s
      timeout: 10s
      retries: 30
    depends_on:
      server:
        condition: service_healthy

  mysql:
    image: registry.cn-qingdao.aliyuncs.com/kubeoperator/mysql-server:8.0.21-${OS_ARCH}
    container_name: kubeoperator_mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 20
    env_file:
      - ./conf/mysql.env
    volumes:
      - ./conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./conf/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/mysql:/var/lib/mysql

  grafana:
    image: registry.cn-qingdao.aliyuncs.com/kubeoperator/grafana:7.1.0-${OS_ARCH}
    container_name: kubeoperator_grafana
    restart: always
    env_file:
      - ./conf/grafana.env
    volumes:
      - ./conf/grafana.ini:/etc/grafana/grafana.ini
    healthcheck:
      test: ["CMD","ps", "-ef", "|", "grep", "grafana-server"]
      interval: 10s
      timeout: 10s
      retries: 20
    depends_on:
      mysql:
        condition: service_healthy

  webkubectl:
    image: registry.cn-qingdao.aliyuncs.com/kubeoperator/webkubectl:v2.6.0-${OS_ARCH}
    container_name: kubeoperator_webkubectl
    restart: always
    privileged: true
    healthcheck:
      test: ["CMD","curl","localhost:8080"]
      interval: 10s
      timeout: 10s
      retries: 20

  nexus:
    restart: always
    image: registry.cn-qingdao.aliyuncs.com/kubeoperator/nexus3:3.25.0-${OS_ARCH}
    container_name: kubeoperator_nexus
    ports:
      - 8081:8081
      - 8082:8082
      - 8083:8083
    volumes:
      - ./data/nexus-data/:/nexus-data
